function [ dx ] = odefun_quad_6D( t, params, x, u )
%ODEFUN QUAD
%   ode functin for quadrotor
    dx = zeros(6,1);
    dx(1) = x(2);
    dx(2) = (-(1/params.m)*params.transDrag*x(2))+...
          ((-1/params.m)*sin(x(5))*u(1))+...
          ((-1/params.m)*sin(x(5))*u(2));
    dx(3) = x(4);
    dx(4) = (-1/params.m)*(params.m*params.grav + params.transDrag*x(4)) +...
          ((1/params.m)*cos(x(5))*u(1))+...
          ((1/params.m)*cos(x(5))*u(2));
    dx(5) = x(6);
    dx(6) = ((-1/params.Iyy)*params.rotDrag*x(6))+...
          ((-params.l/params.Iyy)*u(1))+...
          ((params.l/params.Iyy)*u(2));
end

